name: prevwinds_backend

dependencies:
  - python=3.8
  - pylint
  - black
  - mypy
  - types-pytz
  - uvicorn
  - pip:
      - aws-sam-cli
      - -r src/requirements.txt
      - -r tests/requirements.txt
