AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  GraphQL hosted in a Lambda function.

Parameters:
  ContentBucket:
    Type: String
    Default: prevailing-winds-data

Globals:
  Function:
    Timeout: 10

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    Auth:
      UsagePlan:
        CreateUsagePlan: PER_API
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 100
          RateLimit: 50

Resources:
  GqlGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: graphql_get.lambda_handler
      Runtime: python3.10
      Events:
        Gql:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
            RestApiId: !Ref ApiDeployment

  GqlPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: graphql_post.lambda_handler
      Runtime: python3.10
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ContentBucket
      Events:
        Gql:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
            RestApiId: !Ref ApiDeployment

  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: stage
      Domain:
        DomainName: backend.prevailing-winds.de
        CertificateArn: arn:aws:acm:us-east-1:484021385160:certificate/d6d871f4-7383-4e80-ada1-d24f6c6bed90
        EndpointConfiguration: EDGE

Outputs:
  GqlApi:
    Description: "API Gateway endpoint URL for the Lambda-GraphQL app"
    Value: !Sub "https://${ApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/stage/graphql/"
  GqlGetFunction:
    Description: "Lambda-GraphQL GET Lambda Function ARN"
    Value: !GetAtt GqlGetFunction.Arn
  GqlGetFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda-GraphQL GET function"
    Value: !GetAtt GqlGetFunctionRole.Arn
  GqlPostFunction:
    Description: "Lambda-GraphQL POST Lambda Function ARN"
    Value: !GetAtt GqlPostFunction.Arn
  GqlPostFunctionIamRole:
    Description: "Implicit IAM Role created for Lambda-GraphQL POST function"
    Value: !GetAtt GqlPostFunctionRole.Arn
